# static columns
SEL_COLS=`time`timestamp`bar`sym`ticker`open`high`low`close
BAR_COL=`bar

# CHUNKING / DATES
DATES_AT_ONCE=7
CARRY_BARS=100    # preload bars per chunk for warmup continuity

# STRATEGY SEMANTICS
HOLD_OVERNIGHT=0
