# --- Context ---
strategy = chan
data     = qi.alpaca
universe = equities1.txt

# --- Timeline ---
interval     = 1Min
start        = 2025.09.19D09:30
end          = 2025.09.19D16:00
warmup       = auto
market_open  = 14:30:00
market_close = 21:00:00

# --- Economics ---
equity   = 100k
leverage = 1.0
fees     = 10bps
slip     = 5bps

# --- Risk ---
max_dd   = 0.15
max_ddd  = 24h
