# --- Context ---
strategy = mr_full
data     = qi.binance
universe = binance1.txt

# --- Timeline ---
interval     = 1m
start        = 2024.07.19D09:30
end          = 2024.09.19D16:00
warmup       = auto

# --- Execution ---
enter_at   = next_open 
enter_slip = 5bps
exit_at    = next_open
exit_slip  = 5bps

# --- Economics ---
initial_equity = 1000
leverage       = 1.0
fees           = 10bps

# --- Risk ---
max_dd  = 0.15
max_ddd = 300