# --- Context ---
strategy = simple_mr1
data     = qi.binance   # or data = /path/to/my/hdb
universe = binance1.txt

# --- Timeline ---
interval      = 1m     # or bars = MyBarTable1m
start         = 2025.09.19D09:30
end           = 2025.09.19D16:00
warmup        = auto     # or warmup = 20 (to skip first 20 bars per sym) 
timeout_bars  = 60

# --- Execution ---
enter_at   = next_open
enter_slip = 5bps
exit_at    = next_open
exit_slip  = 5bps

# --- Economics ---
initial_equity  = 1000
leverage        = 1.0
fees            = 10bps

# --- Risk ---
max_dd   = 0.15
max_ddd  = 300